using System.Collections.Generic;
using BaseArchitecture.Core;
using UnityEngine;

namespace SpaceInvaders.Scenes.Game
{
    [CreateAssetMenu(fileName = "LevelConfig", menuName = "SpaceInvaders/Levels/Level Config")]
    public class LevelConfigSO : ScriptableObject, IRepositoryObject
    {
        [Header("Level Settings")]
        [SerializeField] private int _levelIndex;
        [SerializeField] private LevelTypes _levelType;
        [SerializeField] private List<WaveConfigDTO> _wavesConfigs;

        [HideInInspector] [SerializeField] private int _generatorSeed;

        [Header("Star Rating")]
        [SerializeField] private int _threeStarMaxDamage = 0;

        public virtual int Index => _levelIndex;
        public virtual string LevelName => $"Level {_levelIndex}";
        public virtual LevelTypes LevelType => _levelType;
        public virtual List<WaveConfigDTO> WavesConfigs => _wavesConfigs;
        public virtual int ThreeStarMaxDamage => _threeStarMaxDamage;

        // 0 if this level was never generated by the Level Generator tool; otherwise the seed that produced it.
        public virtual int GeneratorSeed => _generatorSeed;

        public virtual string ObjectID => LevelName;
    }
}